source 'http://gemcutter.org'

gem 'rails',      '3.0.0'
gem 'rack'
gem 'gravtastic'
gem 'later_dude', '>= 0.3.1'
gem 'minimal'
gem 'warden'
gem 'devise'
gem 'sprockets'
gem 'prawn'
gem 'nokogiri'

group :test do
	gem 'mysql2'
	gem 'machinist'
	gem 'faker'
	gem 'cucumber'
	gem 'steam',       '>= 0.0.7'
	gem 'locator',     '>= 0.0.7'
	gem 'rspec'
	gem 'rspec-rails'
	gem 'rcov'
	gem 'launchy'
	gem 'no_peeping_toms'
	gem 'database_cleaner', '>= 0.6.0.rc.3'
end
