source 'http://gemcutter.org'

gem "rails",      '= 3.0.0.beta2'
gem 'rack'
gem 'gravtastic', '>= 2.1.0'
gem 'later_dude', '>= 0.3.1'
gem 'minimal',    '>= 0.0.8'
gem 'warden'
gem 'devise',     '>= 1.1.rc0'
gem 'fastercsv'
gem 'sprockets'

group :test do
	gem 'mysql',      '>= 2.7'
	gem 'ruby-debug'
	gem 'machinist'
	gem 'faker'
	gem 'cucumber'
	gem 'steam', :path => '/Volumes/Users/sven/Development/projects/steam'
	# gem 'steam',       '>= 0.0.7'
	gem 'locator',     '>= 0.0.7'
	gem 'rspec',       '>= 2.0.0.a5'
	gem 'rspec-rails', '>= 2.0.0.a6'
	gem 'rcov'
	gem 'launchy'
	gem 'no_peeping_toms'
end
