source 'http://gemcutter.org'

gem "rails",      '3.0.0'
gem 'rack'
gem 'gravtastic'
gem 'later_dude', '>= 0.3.1'
gem 'minimal'
gem 'warden'
gem 'devise',     '1.1.rc2'
gem 'sprockets'
gem 'prawn'
gem 'fastercsv'
gem 'nokogiri'

group :test do
	gem 'mysql',      '>= 2.7'
	gem 'ruby-debug'
	gem 'machinist'
	gem 'faker'
	gem 'cucumber'
	gem 'steam',       '>= 0.0.7'
	gem 'locator',     '>= 0.0.7'
	gem 'rspec',       '2.0.0.beta.22'
	gem 'rspec-rails', '2.0.0.beta.22'
	gem 'rcov'
	gem 'launchy'
	gem 'no_peeping_toms'
	gem 'database_cleaner'
end
