//= require "vendor/jquery/jquery"
//= require "vendor/jquery/jquery-ui"
//= require "vendor/jquery/jquery-plugin-form"
//= require "vendor/jquery/jquery-plugin-quicksearch"
//= require "ext"
//= require "shiftplan"
