icons:
  add:               'f067'
  edit:              'f044'
  destroy:           'f00d'
  copy_week:         'f079'
  comment:           'f075'
  no_comment:        'f0e5'
  reply:             'f053'
  envelope:          'f0e0'
  dashboard:         'f0e4'
  organization:      'f015'
  plans:             'f073'
  news:              'f0e7'
  employees:         'f007'
  teams:             'f0e8'
  settings:          'f007'
  signup:            'f007'
  signout:           'f08b'
  signin:            'f090'
  expand:            'f0da'
  collapse:          'f0d7'
  hide:              'f0d9'
  check:             'f00c'
  notice:            'f00c'
  info:              'f00c'
  warning:           'f071'
  error:             'f071'
  alert:             'f00d'
#
# deprecated icons:
#   new_plan:          'plus'
#   new_scheduling:    'plus'
#   new_organization:  'plus'
#   edit:              'edit'
#   update:            'ok-circle'
#   invite:            'user'
#   reinvite:          'user'
#   comments_count:    'comment'
#   back:              'arrow-left'
#   send_invitation:   'envelope'
#   left_caret:        'f0d9'

