#!/bin/sh

# set JAVA stuff for installing rjb
export JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${JAVA_HOME}/jre/lib/i386:${JAVA_HOME}/jre/lib/i386/client
echo $JAVA_HOME
echo $LD_LIBRARY_PATH

# get latest steam code, the version of locactor gem has to be checked manually
# if steam gets more stable we could comment out the update step
# steam is now a gem and not a plugin
#ODIR=`pwd` && cd /var/www/shiftplan/shared/vendor/plugins/steam && git pull && cd $ODIR
ln -nfs /var/www/shiftplan/shared/vendor/htmlunit-2.6 vendor/htmlunit-2.6

# create database configuration
ln -nfs /var/www/shiftplan/shared/config/database.yml.test config/database.yml

# run bundler stuff 
# run bundle install only if bundle check misses something
# taking out the --relock as we don't change the Gemfile.lock
bundle check || env PATH=$PATH bundle install

# prepare test db
rake environment RAILS_ENV=test db:drop db:create db:migrate

# create tmp/pids dir if not already exists and set chmod 666
mkdir -p -m 766 tmp/pids

# start the test server into background
# as long we use rails3beta1 we have to pass RAILS_ENV to the server
# this is solved 5 days after releasing beta1 (LH #3877)
#nohup bundle exec rails server -p 3000 -e test > log/server.log &
nohup env RAILS_ENV=test bundle exec rails server -p 3000 > log/server.log &

# wait for starting server and run the tests
sleep 10 && bundle exec cucumber -b features RAILS_ENV=test && bundle exec rspec ./spec
STATUS=`echo $?`

# stop the before started test server
if [ -f 'tmp/pids/server.pid' ]
then
  kill -9 `cat tmp/pids/server.pid`
  rm tmp/pids/server.pid
fi

exit $STATUS
