#!/bin/bash

. script/_lib

# run bundle install only if bundle check misses something
# taking out the --relock as we don't change the Gemfile.lock
bundle check || bundle install || exit 128

header "rSpec"
bundle exec rspec --color ./spec                                 || exit 8

header "Jasmine"
xvfb-run bundle exec guard-jasmine                               || exit 4

header "Cucumber with chrome"
CAPYBARA_CHROME=yes bundle exec cucumber --profile ci features -t @javascript || exit 2

header "Cucumber with firefox"
bundle exec cucumber --profile ci features                                    || exit 1

header "Done"
