#!/usr/bin/env ruby

debug = ENV['DEBUG']
require 'pry' if debug
require 'cinch'
$:.unshift File.expand_path('../../lib/cinch', __FILE__)

require 'hello'

bot = Cinch::Bot.new do
  configure do |c|
    c.server          = "irc.freenode.org"
    c.nick            = debug ? 'lanpy' : 'cilea'
    c.channels        = [debug ? "#lanpartei" : "#shiftplan"]
    c.verbose         = true
    c.plugins.plugins = [Hello]
  end
end

bot.start
